services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - ./apps/client/.env
    depends_on:
      - server
    networks:
      - dupme-network

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '5001:5001'
    environment:
      - NODE_ENV=production
    env_file:
      - apps/server/.env
    networks:
      - dupme-network

networks:
  dupme-network:
    driver: bridge
    attachable: true

volumes:
  pnpm-store:
    name: pnpm-store
